### ISSUE TITLE
Improve the efficiency of protocol serialization.

### ISSUE THREAD

**Issue by copiousfreetime** [copiousfreetime/kjess#22]

**Comment by olnrao** [comment]
Please note that actual message is a gzip file in some cases (in case of FTP Server downloads).  In case of HTTP Payloads, it is plain XML text.

The message lengths are quite varying.  5 KB to 1.7 MB. 

Thanks,
Laxmi

**Comment by copiousfreetime** [comment]
I've done a bit of a benchmark, feel free to make sure you get something similar...

https://gist.github.com/copiousfreetime/7673952#file-str-append-bench-rb

I've played with a bit in a few other scenarious, with higher counts and it looks like 'Array#join 4' is probably the most efficient version of it.

**Comment by copiousfreetime** [comment]
@olnrao let me know if that works for you and if so I'll push a new release

**Comment by olnrao** [comment]
Yes, this seems much better.  Thanks for your time.  I was searching for a way to hint StringIO about the buffer to allocate so that we could make it efficient.  For example:
a = "foo"
b = "bar"
c = "fun"
d = "test"
s = StringIO.new(a.size + b.size + c.size + d.size)

This would be apt for protocol building.  We know incoming payload size, we know 'rough upper limit' other protocol portion that would make it simple and clear.  I looked down into Ruby implementation of StringIO and it seemed to be quite easy to add.  May be for next time.

For now, Array.join in a way is providing hints to Ruby about the size of buffer to allocate (and avoid repeated allocations and memory copies).  Array.join is definitely a superb idea.

Thanks again for all your hard work.
Laxmi
